let name = "Hemfix";
let number = 14;
let age = 19;
let someAnimals = "Кот, Конь, Волк";
let boolean = true;
console.log(typeof name);
console.log(typeof number);
console.log(typeof someAnimals);
console.log(name.length);
console.log("Меня зовут " + name);
console.log("Мне " + age + " лет");